  name: Mafia
  main: io.dogsbean.mafia.Main
  version: 1.0
  commands:
    start:
      description: "start the game."
      aliases: [ start ]
    end:
      description: "end the game."
      aliases: [ end ]